module.exports = {
  extends: [
    "stylelint-config-standard-scss",
    "stylelint-config-recess-order",
    "stylelint-config-html",
  ],
  rules: {
    "keyframes-name-pattern": null,
    "scss/at-function-pattern": null,
    "scss/at-mixin-pattern": null,
    "scss/dollar-variable-pattern": null,
    "scss/percent-placeholder-pattern": null,
    "scss/selector-no-union-class-name": true,
    "scss/double-slash-comment-whitespace-inside": null,
    "scss/no-global-function-names": null,
    "scss/selector-no-union-class-name": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "function-name-case": null,
    "no-descending-specificity": null,
    "media-feature-name-no-unknown": null,
    "custom-property-pattern": null,
  },
  ignoreFiles: ["dist/**", "htdocs/**", "**/node_modules/**"],
};
